apiVersion: apps/v1
kind: Deployment
metadata:
  name: version-app-v1
  labels:
    app: version-app
    version: 1.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: version-app
      version: 1.0.0
  template:
    metadata:
      labels:
        app: version-app
        version: 1.0.0
    spec:
      containers:
      - name: version-container
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-volume
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: config-volume
        configMap:
          name: version-config-v1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: version-config-v1
data:
  default.conf: |
    server {
        listen 80;
        location / {
            return 200 "Version: 1.0.0\n";
            add_header Content-Type text/plain;
        }
    }